name: Run XCode
# on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Version'     
        required: true
        default: '4.0.1'
jobs:
  build:
    runs-on: macOS-latest
    steps:
    # - name: Install xcode tools
    #   run: sudo xcode-select --install
    # - name: Install brew
    #   run:  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # - name: Install svn
    #   run:  brew install svn
    - name: Install cocoapods
      run:  gem install cocoapods
    ### https://github.com/Kitware/CMake/releases/download/v3.11.2/cmake-3.11.2-Darwin-x86_64.dmg
    - name: Check cmake 
      run: cmake --version
    - name: Check clang
      run: ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/
    - name: Patch __bsfd
      run: cat /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/ia32intrin.h
    ### Checks-out repository under $GITHUB_WORKSPACE, so job can access it
    - name: Checkout ios
      uses: actions/checkout@v2
      with:
        path: ios
    - name: Checkout android
      uses: actions/checkout@v2
      with:
        repository: osmandapp/OsmAnd
        path: android
    - name: Checkout build
      uses: actions/checkout@v2
      with:
        repository: osmandapp/OsmAnd-build
        path: build
    - name: Checkout core legacy
      uses: actions/checkout@v2
      with:
        repository: osmandapp/OsmAnd-core-legacy
        path: core-legacy
    - name: Checkout core
      uses: actions/checkout@v2
      with:
        repository: osmandapp/OsmAnd-core
        path: core
    - name: Checkout help
      uses: actions/checkout@v2
      with:
        repository: osmandapp/osmandapp.github.io
        path: help
    - name: Checkout resources
      uses: actions/checkout@v2
      with:
        repository: osmandapp/OsmAnd-resources
        path: resources

    # Select xcode
    - name: Force XCode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
#      with:
#        token: ${{ secrets.CHECKOUT_KEY }}
    # Run build
    - name: Prepare to build
      run: exec ios/prepare.sh
    - name: Testing iOS app
      run: xcodebuild -workspace ios/OsmAnd.xcworkspace \
            -scheme OsmAnd\ Maps\ Release \
            -sdk iphoneos \
            -configuration AppStoreDistribution \
            -archivePath build/OsmAndMaps.xcarchive \
            clean archive | xcpretty
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: OsmAndMaps.xcarchive
        path: build/OsmAndMaps.xcarchive